name: Daily Medium Trends Pipline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * * *"

jobs:
  run-script:
    runs-on: macOS

    steps:
      - name: Checkout repository 🛎
        uses: actions/checkout@v2

      - name: Setup Node.js ⭐️
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies 🔩
        run: yarn

      - name: Run Script 🏃‍♀️
        run: node index.js

      - name: Login Github 🔑
        run: |
          git config --global user.name "ria-ahyoung"
          git config --global user.email "ria.ahyoung@gmail.com"

      - name: Commit Github 🔖
        run: |
          git pull origin main
          git add .
          git commit -m "feat: 🎉 update `${{ format('{0:yyyy/MM/dd}', github.run_number) }}` Tech Trends"

      - name: Push Github 💻
        run: git push
